CMAKE_MINIMUM_REQUIRED(VERSION 3.5)

PROJECT("libexword-re")

FIND_PACKAGE(PkgConfig REQUIRED)
PKG_CHECK_MODULES(LIBUSB libusb-1.0)

IF(LIBUSB_FOUND)
    INCLUDE_DIRECTORIES(${LIBUSB_INCLUDE_DIRS})
    LINK_DIRECTORIES(${LIBUSB_LIBRARY_DIRS})
ENDIF()


SET(BIN_NAME "exword")
INCLUDE_DIRECTORIES(${PROJECT_SOURCE_DIR}/includes)
FILE(GLOB srcfile "databuffer.c" "dict.c" "exword.c" "obex.c" "util.c" )
ADD_EXECUTABLE(${BIN_NAME} main.c ${srcfile})

TARGET_LINK_LIBRARIES(${BIN_NAME} ${LIBUSB_LIBRARIES} readline)
